-- Enable foreign key enforcement
PRAGMA foreign_keys = 0;

DROP TABLE IF EXISTS timeseries;

CREATE TABLE timeseries
(
    measurement_id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp      REAL NOT NULL,
    value          REAL NOT NULL,
    datafile_id    INTEGER,
    FOREIGN KEY (datafile_id) REFERENCES datafile (datafile_id)
);

DROP TABLE IF EXISTS datafile;

CREATE TABLE datafile
(
    datafile_id VARCHAR(100) PRIMARY KEY NOT NULL UNIQUE,
--   datafile_id      INTEGER NOT NULL UNIQUE ,
    datafile_name TEXT NOT NULL UNIQUE
);

DROP TABLE IF EXISTS investigation;

CREATE TABLE investigation
(
    investigation_id VARCHAR(100) PRIMARY KEY NOT NULL UNIQUE,
    investigation_name     TEXT NOT NULL UNIQUE,
    investigation_file_url TEXT NOT NULL UNIQUE
);

DROP TABLE IF EXISTS investigation_datafile;

CREATE TABLE investigation_datafile
(
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    investigation_id VARCHAR(100) NOT NULL,
    datafile_id      VARCHAR(100) NOT NULL,
    FOREIGN KEY (datafile_id) REFERENCES datafile (datafile_id),
    FOREIGN KEY (investigation_id) REFERENCES investigation (investigation_id)
);

DROP TABLE IF EXISTS definition;

CREATE TABLE definition
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    table_name TEXT NOT NULL CHECK ( table_name IN ('timeseries', 'datafile', 'investigation', 'investigation_datafile',
                                                    'definition')),
    term       TEXT NOT NULL,
    type       TEXT NOT NULL CHECK ( type IN ('Table name', 'Table attribute')),
    definition TEXT NOT NULL,
    datatype   TEXT CHECK ( datatype IN ('Integer', 'Datetime', 'Text', 'Float', NULL) )
);

-- INSERT DATA

-- INSERT INTO timeseries (timestamp, value, datafile_id)
-- VALUES
--     (0.0, 5.225863831, 1),
--     (0.05, 1.792715056, 1),
--     (0.1, 5.905806673, 1),
--     (0.15, 3.412498741, 1),
--     (0.2, 5.872433286, 1),
--     (0.25, 4.123323214, 2),
--     (0.3, 5.656794558, 2),
--     (0.35, 1.731511753, 2),
--     (0.4, 3.323698468, 2),
--     (0.45, 4.771215442, 2),
--     (0.5, 4.465495613, 2),
--     (0.55, 1.358141583, 3),
--     (0.6, 2.705413063, 3),
--     (0.65, 4.303529958, 3),
--     (0.7, 1.538028614, 3),
--     (0.75, 2.771614835, 3),
--     (0.8, 2.425007444, 4),
--     (0.85, 4.519839583, 4),
--     (0.9, 3.803225164, 4),
--     (0.95, 4.332095261, 4),
--     (1.0, 3.327061037, 4),
--     (1.05, 1.602115659, 4)
-- ;
--
-- INSERT INTO datafile (datafile_id, datafile_name)
-- VALUES
--     (1,'DATAFILE-a.a.txt'),
--     (2, 'DATAFILE-a.b.txt'),
--     (3, 'DATAFILE-a.c.txt'),
--     (4, 'DATAFILE-a.d.txt')
-- ;
--
-- INSERT INTO investigation (investigation_name, investigation_file_url)
-- VALUES
--     ('TECHPORT', 'https://www.example.org'),
--     ('DEFENSIE', 'https://www.example.org/second')
-- ;
--
-- INSERT INTO investigation_datafile (investigation_id, datafile_id)
-- VALUES
--     (1, 1),
--     (1, 2),
--     (2, 3),
--     (2, 4)
-- ;

INSERT INTO definition (table_name, term, type, definition, datatype)
VALUES ('timeseries', 'timeseries', 'Table name',
        'Table containing measurement values where the values are stored as a timeseries.', NULL),
       ('timeseries', 'value', 'Table attribute', 'Measurement value at a specific timestamp.', 'Float'),
       ('timeseries', 'measurement_id', 'Table attribute',
        'ID of a single value. Automatically generated by the database.', 'Integer'),
       ('timeseries', 'timestamp', 'Table attribute', 'Timestamp of a single value', 'Datetime'),
       ('timeseries', 'datafile_id', 'Table attribute',
        'ID of a source file / data file in which the measurement value is stored. Foreign key to table "datafile".',
        'Integer'),

       ('datafile', 'datafile', 'Table name', 'Table containing source files / data files in which data is stored.',
        NULL),
       ('datafile', 'datafile_id', 'Table attribute', 'ID of a data file. Automatically generated by the database.',
        'Integer'),
       ('datafile', 'datafile_name', 'Table attribute', 'Name of a data file.', 'Text'),

       ('investigation', 'investigation', 'Table name',
        'Table containing investigations (as in the ISA data standard, see https://isa-specs.readthedocs.io/en/latest/isamodel.html).',
        NULL),
       ('investigation', 'investigation_id', 'Table attribute',
        'ID of an investigation. Automatically generated by the database.', 'Integer'),
       ('investigation', 'investigation_name', 'Table attribute', 'Name of an investigation.', 'Text'),
       ('investigation', 'investigation_file_url', 'Table attribute',
        'URL of the investigation file containing the investigation data.', 'Text'),

       ('investigation_datafile', 'investigation_datafile', 'Table name',
        'Relationship table between investigations and data files. An investigation contains 1 or n data files.', NULL),
       ('investigation_datafile', 'id', 'Table attribute',
        'ID of the relationship between an investigation and a data file. Automatically generated by the database.',
        'Integer'),
       ('investigation_datafile', 'investigation_id', 'Table attribute',
        'ID of an investigation in the relationship table.', 'Integer'),
       ('investigation_datafile', 'datafile_id', 'Table attribute', 'ID of a data file in the relationship table.',
        'Integer'),


       ('definition', 'definition', 'Table name', 'Table containing definitions of terms used in the database.', NULL),
       ('definition', 'id', 'Table attribute', 'ID of a definition. Automatically generated by the database.',
        'Integer'),
       ('definition', 'table_name', 'Table attribute', 'Name of the table to which the term belongs.', 'Text'),
       ('definition', 'term', 'Table attribute', 'Term that is defined.', 'Text'),
       ('definition', 'type', 'Table attribute', 'Type of the term, either "Table name" or "Table attribute".', 'Text'),
       ('definition', 'definition', 'Table attribute', 'Definition of the term.', 'Text'),
       ('definition', 'datatype', 'Table attribute',
        'Data type of the term, e.g. "Integer", "Datetime", "Text", "Float". If NULL, no data type is specified.',
        'Text')
;